package org.ecnu.orm;

// Generated 2013-5-10 0:34:16 by Hibernate Tools 3.4.0.CR1

/**
 * ChannelGroup generated by hbm2java
 */
public class ChannelGroup implements java.io.Serializable {

	private Long id;
	private Wares wares;
	private String versionName;
	private String channelId;
	private Integer normalStock;
	private Integer stdOut;
	private String type;
	private String des;
	private String lastTime;

	public ChannelGroup() {
	}

	public ChannelGroup(Wares wares) {
		this.wares = wares;
	}

	public ChannelGroup(Wares wares, String versionName, String channelId,
			Integer normalStock, Integer stdOut, String type, String des,
			String lastTime) {
		this.wares = wares;
		this.versionName = versionName;
		this.channelId = channelId;
		this.normalStock = normalStock;
		this.stdOut = stdOut;
		this.type = type;
//		this.desc = desc;
		this.lastTime = lastTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Wares getWares() {
		return this.wares;
	}

	public void setWares(Wares wares) {
		this.wares = wares;
	}

	public String getVersionName() {
		return this.versionName;
	}

	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}

	public String getChannelId() {
		return this.channelId;
	}

	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

	public Integer getNormalStock() {
		return this.normalStock;
	}

	public void setNormalStock(Integer normalStock) {
		this.normalStock = normalStock;
	}

	public Integer getStdOut() {
		return this.stdOut;
	}

	public void setStdOut(Integer stdOut) {
		this.stdOut = stdOut;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	public String getDes() {
		return des;
	}

	public void setDes(String des) {
		this.des = des;
	}

}
