package org.ecnu.orm;

// Generated 2013-4-13 12:14:00 by Hibernate Tools 3.4.0.CR1

/**
 * DepotHis generated by hbm2java
 */
public class DepotHis implements java.io.Serializable {

	private Long depotHisId;
	private long userId;
	private String employeeName;
	private String depotWareName;
	private Integer depotWareNum;
	private Integer depotWarePrice;
	private String depotType;
	private String depotOperator;
	private String lastTime;
	private String shippingId;

	public DepotHis() {
	}

	public DepotHis(long userId, String employeeName) {
		this.userId = userId;
		this.employeeName = employeeName;
	}

	public DepotHis(long userId, String employeeName, String depotWareName,
			Integer depotWareNum, Integer depotWarePrice, String depotType,
			String depotOperator, String shippingId, String lastTime) {
		this.userId = userId;
		this.employeeName = employeeName;
		this.depotWareName = depotWareName;
		this.depotWareNum = depotWareNum;
		this.depotWarePrice = depotWarePrice;
		this.depotType = depotType;
		this.depotOperator = depotOperator;
		this.shippingId = shippingId;
		this.lastTime = lastTime;
	}

	public Long getDepotHisId() {
		return this.depotHisId;
	}

	public void setDepotHisId(Long depotHisId) {
		this.depotHisId = depotHisId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getDepotWareName() {
		return this.depotWareName;
	}

	public void setDepotWareName(String depotWareName) {
		this.depotWareName = depotWareName;
	}

	public Integer getDepotWareNum() {
		return this.depotWareNum;
	}

	public void setDepotWareNum(Integer depotWareNum) {
		this.depotWareNum = depotWareNum;
	}

	public Integer getDepotWarePrice() {
		return this.depotWarePrice;
	}

	public void setDepotWarePrice(Integer depotWarePrice) {
		this.depotWarePrice = depotWarePrice;
	}

	public String getDepotType() {
		return this.depotType;
	}

	public void setDepotType(String depotType) {
		this.depotType = depotType;
	}

	public String getDepotOperator() {
		return this.depotOperator;
	}

	public void setDepotOperator(String depotOperator) {
		this.depotOperator = depotOperator;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	public String getShippingId() {
		return shippingId;
	}

	public void setShippingId(String shippingId) {
		this.shippingId = shippingId;
	}

}
