package org.ecnu.orm;

// Generated 2013-4-27 15:05:46 by Hibernate Tools 3.4.0.CR1

/**
 * Depot generated by hbm2java
 */
public class Depot implements java.io.Serializable {

	private Long depotId;
	private Shipping shipping;
	private Wares wares;
	private String employeeName;
	private String depotWareName;
	private Integer depotWareNum;
	private Integer depotWarePrice;
	private String depotType;
	private String depotOperator;
	private String remark;
	private String lastTime;

	public Depot() {
	}

	public Depot(String employeeName) {
		this.employeeName = employeeName;
	}

	public Depot(Shipping shipping, Wares wares, String employeeName,
			String depotWareName, Integer depotWareNum, Integer depotWarePrice,
			String depotType, String depotOperator, String remark,
			String lastTime) {
		this.shipping = shipping;
		this.wares = wares;
		this.employeeName = employeeName;
		this.depotWareName = depotWareName;
		this.depotWareNum = depotWareNum;
		this.depotWarePrice = depotWarePrice;
		this.depotType = depotType;
		this.depotOperator = depotOperator;
		this.remark = remark;
		this.lastTime = lastTime;
	}

	public Long getDepotId() {
		return this.depotId;
	}

	public void setDepotId(Long depotId) {
		this.depotId = depotId;
	}

	public Shipping getShipping() {
		return this.shipping;
	}

	public void setShipping(Shipping shipping) {
		this.shipping = shipping;
	}

	public Wares getWares() {
		return this.wares;
	}

	public void setWares(Wares wares) {
		this.wares = wares;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getDepotWareName() {
		return this.depotWareName;
	}

	public void setDepotWareName(String depotWareName) {
		this.depotWareName = depotWareName;
	}

	public Integer getDepotWareNum() {
		return this.depotWareNum;
	}

	public void setDepotWareNum(Integer depotWareNum) {
		this.depotWareNum = depotWareNum;
	}

	public Integer getDepotWarePrice() {
		return this.depotWarePrice;
	}

	public void setDepotWarePrice(Integer depotWarePrice) {
		this.depotWarePrice = depotWarePrice;
	}

	public String getDepotType() {
		return this.depotType;
	}

	public void setDepotType(String depotType) {
		this.depotType = depotType;
	}

	public String getDepotOperator() {
		return this.depotOperator;
	}

	public void setDepotOperator(String depotOperator) {
		this.depotOperator = depotOperator;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

}
