package org.ecnu.orm;

// Generated 2013-4-27 23:42:34 by Hibernate Tools 3.4.0.CR1

/**
 * Money generated by hbm2java
 */
public class Money implements java.io.Serializable {

	private Long moneyId;
	private String nodeName;
	private String employeeName;
	private String moneyCount;
	private int moneyIn;
	private String moneyOperator;
	private String type;
	private String remark;
	private String lastTime;

	public Money() {
	}

	public Money(String nodeName, String employeeName, String moneyCount,
			int moneyIn, String moneyOperator, String type, String remark,
			String lastTime) {
		this.nodeName = nodeName;
		this.employeeName = employeeName;
		this.moneyCount = moneyCount;
		this.moneyIn = moneyIn;
		this.moneyOperator = moneyOperator;
		this.type = type;
		this.remark = remark;
		this.lastTime = lastTime;
	}

	public Long getMoneyId() {
		return this.moneyId;
	}

	public void setMoneyId(Long moneyId) {
		this.moneyId = moneyId;
	}

	public String getNodeName() {
		return this.nodeName;
	}

	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getMoneyCount() {
		return this.moneyCount;
	}

	public void setMoneyCount(String moneyCount) {
		this.moneyCount = moneyCount;
	}

	public int getMoneyIn() {
		return this.moneyIn;
	}

	public void setMoneyIn(int moneyIn) {
		this.moneyIn = moneyIn;
	}

	public String getMoneyOperator() {
		return this.moneyOperator;
	}

	public void setMoneyOperator(String moneyOperator) {
		this.moneyOperator = moneyOperator;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

}
