package org.ecnu.orm;

// Generated 2013-4-19 10:10:02 by Hibernate Tools 3.4.0.CR1

/**
 * MystockHis generated by hbm2java
 */
public class MyStockHis implements java.io.Serializable {

	private Long stockHisId;
	private String employeeName;
	private String year;
	private String month;
	private String wareCode;
	private String wareName;
	private Integer depotWareNum;
	private Integer checkStoreNum;
	private Integer currentWareNum;
	private Integer depotWareCost;
	private String type;
	private String lastTime;

	public MyStockHis() {
	}

	public MyStockHis(String employeeName) {
		this.employeeName = employeeName;
	}

	public MyStockHis(String employeeName, String year, String month,
			String wareCode, String wareName, Integer depotWareNum, Integer checkStoreNum,
			Integer currentWareNum, Integer depotWareCost, String type,
			String lastTime) {
		this.employeeName = employeeName;
		this.year = year;
		this.month = month;
		this.wareCode = wareCode;
		this.wareName = wareName;
		this.depotWareNum = depotWareNum;
		this.currentWareNum = currentWareNum;
		this.checkStoreNum = checkStoreNum;
		this.depotWareCost = depotWareCost;
		this.type = type;
		this.lastTime = lastTime;
	}

	public Long getStockHisId() {
		return this.stockHisId;
	}

	public void setStockHisId(Long stockHisId) {
		this.stockHisId = stockHisId;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getWareCode() {
		return this.wareCode;
	}

	public void setWareCode(String wareCode) {
		this.wareCode = wareCode;
	}

	public String getWareName() {
		return this.wareName;
	}

	public void setWareName(String wareName) {
		this.wareName = wareName;
	}

	public Integer getDepotWareNum() {
		return this.depotWareNum;
	}

	public void setDepotWareNum(Integer depotWareNum) {
		this.depotWareNum = depotWareNum;
	}

	public Integer getCurrentWareNum() {
		return this.currentWareNum;
	}

	public void setCurrentWareNum(Integer currentWareNum) {
		this.currentWareNum = currentWareNum;
	}

	public Integer getDepotWareCost() {
		return this.depotWareCost;
	}

	public void setDepotWareCost(Integer depotWareCost) {
		this.depotWareCost = depotWareCost;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	public Integer getCheckStoreNum() {
		return checkStoreNum;
	}

	public void setCheckStoreNum(Integer checkStoreNum) {
		this.checkStoreNum = checkStoreNum;
	}

}
