package org.ecnu.orm;

// Generated 2013-3-12 14:15:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * NodeInfo generated by hbm2java
 */
public class NodeInfo implements java.io.Serializable {

	private String nodeId;
	private NodeGroupInfo nodeGroupInfo;
	private String nodeName;
	private String versionName;//货道组的版本名称，从而获得一组货道，新增时读取所有货道后插入到channelinfo表中
	private String isAssign;
	private String nodeStatus;
	private String macAddr;
	private String simNo;
	private String machineType;
	private String monopoly;
	private String nodeAddr;
	private String nodeFrom;//1.oracle；2.2.0新建
	private Set<ChannelInfo> channelInfos = new HashSet<ChannelInfo>(0);

	public NodeInfo() {
	}

	public NodeInfo(String nodeId) {
		this.nodeId = nodeId;
	}

	public NodeInfo(String nodeId, NodeGroupInfo nodeGroupInfo, String versionName,
			String nodeName, String isAssign, String nodeStatus, String macAddr, String simNo,
			String machineType, String monopoly, String nodeAddr, String nodeFrom,
			Set<ChannelInfo> channelInfos) {
		this.nodeId = nodeId;
		this.nodeGroupInfo = nodeGroupInfo;
		this.nodeName = nodeName;
		this.versionName = versionName;
		this.isAssign = isAssign;
		this.nodeStatus = nodeStatus;
		this.macAddr = macAddr;
		this.simNo = simNo;
		this.machineType = machineType;
		this.monopoly = monopoly;
		this.nodeAddr = nodeAddr;
		this.nodeFrom = nodeFrom;
		this.channelInfos = channelInfos;
	}

	public String getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(String nodeId) {
		this.nodeId = nodeId;
	}

	public NodeGroupInfo getNodeGroupInfo() {
		return this.nodeGroupInfo;
	}

	public void setNodeGroupInfo(NodeGroupInfo nodeGroupInfo) {
		this.nodeGroupInfo = nodeGroupInfo;
	}

	public String getNodeName() {
		return this.nodeName;
	}

	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

	public String getIsAssign() {
		return isAssign;
	}

	public void setIsAssign(String isAssign) {
		this.isAssign = isAssign;
	}

	public String getNodeStatus() {
		return this.nodeStatus;
	}

	public void setNodeStatus(String nodeStatus) {
		this.nodeStatus = nodeStatus;
	}

	public String getMacAddr() {
		return this.macAddr;
	}

	public void setMacAddr(String macAddr) {
		this.macAddr = macAddr;
	}

	public String getSimNo() {
		return this.simNo;
	}

	public void setSimNo(String simNo) {
		this.simNo = simNo;
	}

	public String getMachineType() {
		return this.machineType;
	}

	public void setMachineType(String machineType) {
		this.machineType = machineType;
	}

	public String getMonopoly() {
		return this.monopoly;
	}

	public void setMonopoly(String monopoly) {
		this.monopoly = monopoly;
	}

	public String getNodeAddr() {
		return this.nodeAddr;
	}

	public void setNodeAddr(String nodeAddr) {
		this.nodeAddr = nodeAddr;
	}

	public Set<ChannelInfo> getChannelInfos() {
		return this.channelInfos;
	}

	public void setChannelInfos(Set<ChannelInfo> channelInfos) {
		this.channelInfos = channelInfos;
	}

	public String getVersionName() {
		return versionName;
	}

	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}

	public String getNodeFrom() {
		return nodeFrom;
	}

	public void setNodeFrom(String nodeFrom) {
		this.nodeFrom = nodeFrom;
	}

}
