package org.ecnu.orm;

// Generated 2013-4-19 10:10:02 by Hibernate Tools 3.4.0.CR1

/**
 * Profit generated by hbm2java
 */
public class Profit implements java.io.Serializable {

	private Long profitId;
//	private long userId;
	private String employeeName;
	private String year;
	private String month;
	private Integer turnOverCard;
	private Integer turnOverCash;
	private Integer moneyCount;//上缴金额总数
	private Integer loactionAllowance;
	private Integer locationCost;
	private Integer carGasCost;
	private Integer carRepaireCost;
	private Integer manageCost;//为总营业额的10%
	private Integer wages;
	private Integer profit;
	private Integer insurances;
	private Integer cost1;//其他费用
	private Integer wareCost;
	private Integer cost3;
	private Integer cost4;
	private Integer cost5;
	private Integer cost6;//税收（商品收入+补贴-成本）*系数
	private String lastTime;
	private String type;

	public Profit() {
	}

	public Profit(String employeeName, String year, String month,
			Integer turnOverCard, Integer turnOverCash, Integer moneyCount,
			Integer loactionAllowance, Integer locationCost,
			Integer carGasCost, Integer carRepaireCost, Integer manageCost,
			Integer wages, Integer profit, Integer insurances, Integer cost1,
			Integer wareCost, Integer cost3, Integer cost4, Integer cost5,
			Integer cost6, String lastTime, String type) {
		this.employeeName = employeeName;
		this.year = year;
		this.month = month;
		this.turnOverCard = turnOverCard;
		this.turnOverCash = turnOverCash;
		this.moneyCount = moneyCount;
		this.loactionAllowance = loactionAllowance;
		this.locationCost = locationCost;
		this.carGasCost = carGasCost;
		this.carRepaireCost = carRepaireCost;
		this.manageCost = manageCost;
		this.wages = wages;
		this.profit = profit;
		this.insurances = insurances;
		this.cost1 = cost1;
		this.wareCost = wareCost;
		this.cost3 = cost3;
		this.cost4 = cost4;
		this.cost5 = cost5;
		this.cost6 = cost6;
		this.lastTime = lastTime;
		this.type = type;
	}

	public Long getProfitId() {
		return this.profitId;
	}

	public void setProfitId(Long profitId) {
		this.profitId = profitId;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public Integer getTurnOverCard() {
		return this.turnOverCard;
	}

	public void setTurnOverCard(Integer turnOverCard) {
		this.turnOverCard = turnOverCard;
	}

	public Integer getTurnOverCash() {
		return this.turnOverCash;
	}

	public void setTurnOverCash(Integer turnOverCash) {
		this.turnOverCash = turnOverCash;
	}

	public Integer getMoneyCount() {
		return this.moneyCount;
	}

	public void setMoneyCount(Integer moneyCount) {
		this.moneyCount = moneyCount;
	}

	public Integer getLoactionAllowance() {
		return this.loactionAllowance;
	}

	public void setLoactionAllowance(Integer loactionAllowance) {
		this.loactionAllowance = loactionAllowance;
	}

	public Integer getLocationCost() {
		return this.locationCost;
	}

	public void setLocationCost(Integer locationCost) {
		this.locationCost = locationCost;
	}

	public Integer getCarGasCost() {
		return this.carGasCost;
	}

	public void setCarGasCost(Integer carGasCost) {
		this.carGasCost = carGasCost;
	}

	public Integer getCarRepaireCost() {
		return this.carRepaireCost;
	}

	public void setCarRepaireCost(Integer carRepaireCost) {
		this.carRepaireCost = carRepaireCost;
	}

	public Integer getManageCost() {
		return this.manageCost;
	}

	public void setManageCost(Integer manageCost) {
		this.manageCost = manageCost;
	}

	public Integer getWages() {
		return this.wages;
	}

	public void setWages(Integer wages) {
		this.wages = wages;
	}

	public Integer getProfit() {
		return this.profit;
	}

	public void setProfit(Integer profit) {
		this.profit = profit;
	}

	public Integer getInsurances() {
		return this.insurances;
	}

	public void setInsurances(Integer insurances) {
		this.insurances = insurances;
	}

	public Integer getCost1() {
		return this.cost1;
	}

	public void setCost1(Integer cost1) {
		this.cost1 = cost1;
	}

	public Integer getWareCost() {
		return this.wareCost;
	}

	public void setWareCost(Integer wareCost) {
		this.wareCost = wareCost;
	}

	public Integer getCost3() {
		return this.cost3;
	}

	public void setCost3(Integer cost3) {
		this.cost3 = cost3;
	}

	public Integer getCost4() {
		return this.cost4;
	}

	public void setCost4(Integer cost4) {
		this.cost4 = cost4;
	}

	public Integer getCost5() {
		return this.cost5;
	}

	public void setCost5(Integer cost5) {
		this.cost5 = cost5;
	}

	public Integer getCost6() {
		return this.cost6;
	}

	public void setCost6(Integer cost6) {
		this.cost6 = cost6;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
