package org.ecnu.orm;

// Generated 2013-4-13 12:14:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Long roleId;
	private String roleName;
	private String roleDesc;
	private Long roleFlag;
	private String userRole;
	private String roleRole;
	private String nodeRole;
	private String wareRole;
	private String mapRole;
	private String channelRole;
	private String importRole;
	private String optempRole;
	private String depotRole;
	private String moneyRole;
	private String profitRole;
	private Set<Users> userses = new HashSet<Users>(0);

	public Role() {
	}

	public Role(String roleName, String roleDesc, Long roleFlag,
			String userRole, String roleRole, String nodeRole, String wareRole,
			String mapRole, String channelRole, String importRole,
			String optempRole, String depotRole, String moneyRole,
			String profitRole, Set<Users> userses) {
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.roleFlag = roleFlag;
		this.userRole = userRole;
		this.roleRole = roleRole;
		this.nodeRole = nodeRole;
		this.wareRole = wareRole;
		this.mapRole = mapRole;
		this.channelRole = channelRole;
		this.importRole = importRole;
		this.optempRole = optempRole;
		this.depotRole = depotRole;
		this.moneyRole = moneyRole;
		this.profitRole = profitRole;
		this.userses = userses;
	}

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	public Long getRoleFlag() {
		return this.roleFlag;
	}

	public void setRoleFlag(Long roleFlag) {
		this.roleFlag = roleFlag;
	}

	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	public String getRoleRole() {
		return this.roleRole;
	}

	public void setRoleRole(String roleRole) {
		this.roleRole = roleRole;
	}

	public String getNodeRole() {
		return this.nodeRole;
	}

	public void setNodeRole(String nodeRole) {
		this.nodeRole = nodeRole;
	}

	public String getWareRole() {
		return this.wareRole;
	}

	public void setWareRole(String wareRole) {
		this.wareRole = wareRole;
	}

	public String getMapRole() {
		return this.mapRole;
	}

	public void setMapRole(String mapRole) {
		this.mapRole = mapRole;
	}

	public String getChannelRole() {
		return this.channelRole;
	}

	public void setChannelRole(String channelRole) {
		this.channelRole = channelRole;
	}

	public String getImportRole() {
		return this.importRole;
	}

	public void setImportRole(String importRole) {
		this.importRole = importRole;
	}

	public String getOptempRole() {
		return this.optempRole;
	}

	public void setOptempRole(String optempRole) {
		this.optempRole = optempRole;
	}

	public String getDepotRole() {
		return this.depotRole;
	}

	public void setDepotRole(String depotRole) {
		this.depotRole = depotRole;
	}

	public String getMoneyRole() {
		return this.moneyRole;
	}

	public void setMoneyRole(String moneyRole) {
		this.moneyRole = moneyRole;
	}

	public String getProfitRole() {
		return this.profitRole;
	}

	public void setProfitRole(String profitRole) {
		this.profitRole = profitRole;
	}

	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
