package org.ecnu.orm;

// Generated 2013-4-13 12:14:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
@SuppressWarnings("serial")
public class Users implements java.io.Serializable {

	private Long userId;
	private Role role;
	private UserGroup userGroup;
	private String userName;//系统用户名，登陆用，唯一
	private String passWord;
	private String employeeName;//用户组的意思，也是唯一的，实际使用的字段
	private String personList;//该帐号的真实使用者姓名
	private Long leaderId;
	private String userStatus;
	private Set<Profit> profits = new HashSet<Profit>(0);
	private Set<Depot> depots = new HashSet<Depot>(0);
	private Set<Money> moneies = new HashSet<Money>(0);

	public Users() {
	}

	public Users(String userName) {
		this.userName = userName;
	}

	public Users(Role role, UserGroup userGroup, String userName,
			String passWord, String employeeName, String personList, Long leaderId,
			String userStatus, Set<Profit> profits, Set<Depot> depots,
			Set<Money> moneies) {
		this.role = role;
		this.userGroup = userGroup;
		this.userName = userName;
		this.passWord = passWord;
		this.employeeName = employeeName;
		this.personList = personList;
		this.leaderId = leaderId;
		this.userStatus = userStatus;
		this.profits = profits;
		this.depots = depots;
		this.moneies = moneies;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public UserGroup getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassWord() {
		return this.passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public Long getLeaderId() {
		return this.leaderId;
	}

	public void setLeaderId(Long leaderId) {
		this.leaderId = leaderId;
	}

	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	public Set<Profit> getProfits() {
		return this.profits;
	}

	public void setProfits(Set<Profit> profits) {
		this.profits = profits;
	}

	public Set<Depot> getDepots() {
		return this.depots;
	}

	public void setDepots(Set<Depot> depots) {
		this.depots = depots;
	}

	public Set<Money> getMoneies() {
		return this.moneies;
	}

	public void setMoneies(Set<Money> moneies) {
		this.moneies = moneies;
	}

	public String getPersonList() {
		return personList;
	}

	public void setPersonList(String personList) {
		this.personList = personList;
	}

}
