package org.ecnu.orm;

// Generated 2013-4-27 15:05:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Wares generated by hbm2java
 */
public class Wares implements java.io.Serializable {

	private Long wareId;
	private String wareCode;
	private String wareName;
	private String wareNorm;
	private String wareUnit;
	private Integer wareBasePrice;
	private String wareType;
	private Integer wareMaxPrice;
	private Integer wareMinPrice;
	private String wareDesc;
	private String wareSimpleCode;
	private Long count;
	private String wareStatus;
	private String lastTime;
	private Set<Depot> depots = new HashSet<Depot>(0);

	public Wares() {
	}

	public Wares(String wareCode) {
		this.wareCode = wareCode;
	}

	public Wares(String wareCode, String wareName, String wareNorm,
			String wareUnit, Integer wareBasePrice, String wareType,
			Integer wareMaxPrice, Integer wareMinPrice, String wareDesc,
			String wareSimpleCode, Long count, String wareStatus,
			String lastTime, Set<Depot> depots) {
		this.wareCode = wareCode;
		this.wareName = wareName;
		this.wareNorm = wareNorm;
		this.wareUnit = wareUnit;
		this.wareBasePrice = wareBasePrice;
		this.wareType = wareType;
		this.wareMaxPrice = wareMaxPrice;
		this.wareMinPrice = wareMinPrice;
		this.wareDesc = wareDesc;
		this.wareSimpleCode = wareSimpleCode;
		this.count = count;
		this.wareStatus = wareStatus;
		this.lastTime = lastTime;
		this.depots = depots;
	}

	public Long getWareId() {
		return this.wareId;
	}

	public void setWareId(Long wareId) {
		this.wareId = wareId;
	}

	public String getWareCode() {
		return this.wareCode;
	}

	public void setWareCode(String wareCode) {
		this.wareCode = wareCode;
	}

	public String getWareName() {
		return this.wareName;
	}

	public void setWareName(String wareName) {
		this.wareName = wareName;
	}

	public String getWareNorm() {
		return this.wareNorm;
	}

	public void setWareNorm(String wareNorm) {
		this.wareNorm = wareNorm;
	}

	public String getWareUnit() {
		return this.wareUnit;
	}

	public void setWareUnit(String wareUnit) {
		this.wareUnit = wareUnit;
	}

	public Integer getWareBasePrice() {
		return this.wareBasePrice;
	}

	public void setWareBasePrice(Integer wareBasePrice) {
		this.wareBasePrice = wareBasePrice;
	}

	public String getWareType() {
		return this.wareType;
	}

	public void setWareType(String wareType) {
		this.wareType = wareType;
	}

	public Integer getWareMaxPrice() {
		return this.wareMaxPrice;
	}

	public void setWareMaxPrice(Integer wareMaxPrice) {
		this.wareMaxPrice = wareMaxPrice;
	}

	public Integer getWareMinPrice() {
		return this.wareMinPrice;
	}

	public void setWareMinPrice(Integer wareMinPrice) {
		this.wareMinPrice = wareMinPrice;
	}

	public String getWareDesc() {
		return this.wareDesc;
	}

	public void setWareDesc(String wareDesc) {
		this.wareDesc = wareDesc;
	}

	public String getWareSimpleCode() {
		return this.wareSimpleCode;
	}

	public void setWareSimpleCode(String wareSimpleCode) {
		this.wareSimpleCode = wareSimpleCode;
	}

	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

	public String getWareStatus() {
		return this.wareStatus;
	}

	public void setWareStatus(String wareStatus) {
		this.wareStatus = wareStatus;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	public Set<Depot> getDepots() {
		return this.depots;
	}

	public void setDepots(Set<Depot> depots) {
		this.depots = depots;
	}

}
