package org.ecnu.oracle.orm;

// Generated 2013-3-7 21:12:37 by Hibernate Tools 3.4.0.CR1

/**
 * GroupInfoDtl generated by hbm2java
 */
public class GroupInfoDtl implements java.io.Serializable {

	private GroupInfoDtlId id;
	private String lastTime;

	public GroupInfoDtl() {
	}

	public GroupInfoDtl(GroupInfoDtlId id) {
		this.id = id;
	}

	public GroupInfoDtl(GroupInfoDtlId id, String lastTime) {
		this.id = id;
		this.lastTime = lastTime;
	}

	public GroupInfoDtlId getId() {
		return this.id;
	}

	public void setId(GroupInfoDtlId id) {
		this.id = id;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

}
