package org.ecnu.oracle.orm;

// Generated 2013-3-7 21:12:37 by Hibernate Tools 3.4.0.CR1

/**
 * NodeInfo generated by hbm2java
 */
public class ONodeInfo implements java.io.Serializable {

	private String nodeId;
	private String nodeName;
	private String nodeType;
	private String parentNode;
	private Character nodeStatus;
	private String mainIp;
	private String backupIp;
	private int port;
	private Long QKey;
	private Long QId;
	private Long reqMtype;
	private long commPackLimit;
	private String macAddr;
	private String nodeAddr;
	private String machineType;

	public ONodeInfo() {
	}

	public ONodeInfo(String nodeId, String nodeType, String mainIp, int port,
			long commPackLimit) {
		this.nodeId = nodeId;
		this.nodeType = nodeType;
		this.mainIp = mainIp;
		this.port = port;
		this.commPackLimit = commPackLimit;
	}

	public ONodeInfo(String nodeId, String nodeName, String nodeType,
			String parentNode, Character nodeStatus, String mainIp,
			String backupIp, int port, Long QKey, Long QId, Long reqMtype,
			long commPackLimit, String macAddr, String nodeAddr,
			String machineType) {
		this.nodeId = nodeId;
		this.nodeName = nodeName;
		this.nodeType = nodeType;
		this.parentNode = parentNode;
		this.nodeStatus = nodeStatus;
		this.mainIp = mainIp;
		this.backupIp = backupIp;
		this.port = port;
		this.QKey = QKey;
		this.QId = QId;
		this.reqMtype = reqMtype;
		this.commPackLimit = commPackLimit;
		this.macAddr = macAddr;
		this.nodeAddr = nodeAddr;
		this.machineType = machineType;
	}

	public String getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(String nodeId) {
		this.nodeId = nodeId;
	}

	public String getNodeName() {
		return this.nodeName;
	}

	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

	public String getNodeType() {
		return this.nodeType;
	}

	public void setNodeType(String nodeType) {
		this.nodeType = nodeType;
	}

	public String getParentNode() {
		return this.parentNode;
	}

	public void setParentNode(String parentNode) {
		this.parentNode = parentNode;
	}

	public Character getNodeStatus() {
		return this.nodeStatus;
	}

	public void setNodeStatus(Character nodeStatus) {
		this.nodeStatus = nodeStatus;
	}

	public String getMainIp() {
		return this.mainIp;
	}

	public void setMainIp(String mainIp) {
		this.mainIp = mainIp;
	}

	public String getBackupIp() {
		return this.backupIp;
	}

	public void setBackupIp(String backupIp) {
		this.backupIp = backupIp;
	}

	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public Long getQKey() {
		return this.QKey;
	}

	public void setQKey(Long QKey) {
		this.QKey = QKey;
	}

	public Long getQId() {
		return this.QId;
	}

	public void setQId(Long QId) {
		this.QId = QId;
	}

	public Long getReqMtype() {
		return this.reqMtype;
	}

	public void setReqMtype(Long reqMtype) {
		this.reqMtype = reqMtype;
	}

	public long getCommPackLimit() {
		return this.commPackLimit;
	}

	public void setCommPackLimit(long commPackLimit) {
		this.commPackLimit = commPackLimit;
	}

	public String getMacAddr() {
		return this.macAddr;
	}

	public void setMacAddr(String macAddr) {
		this.macAddr = macAddr;
	}

	public String getNodeAddr() {
		return this.nodeAddr;
	}

	public void setNodeAddr(String nodeAddr) {
		this.nodeAddr = nodeAddr;
	}

	public String getMachineType() {
		return this.machineType;
	}

	public void setMachineType(String machineType) {
		this.machineType = machineType;
	}

}
