package org.ecnu.oracle.orm;

// Generated 2013-3-7 21:12:37 by Hibernate Tools 3.4.0.CR1

/**
 * ParamVersionId generated by hbm2java
 */
public class ParamVersionId implements java.io.Serializable {

	private String nodeId;
	private String paramTag;

	public ParamVersionId() {
	}

	public ParamVersionId(String nodeId, String paramTag) {
		this.nodeId = nodeId;
		this.paramTag = paramTag;
	}

	public String getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(String nodeId) {
		this.nodeId = nodeId;
	}

	public String getParamTag() {
		return this.paramTag;
	}

	public void setParamTag(String paramTag) {
		this.paramTag = paramTag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParamVersionId))
			return false;
		ParamVersionId castOther = (ParamVersionId) other;

		return ((this.getNodeId() == castOther.getNodeId()) || (this
				.getNodeId() != null && castOther.getNodeId() != null && this
				.getNodeId().equals(castOther.getNodeId())))
				&& ((this.getParamTag() == castOther.getParamTag()) || (this
						.getParamTag() != null
						&& castOther.getParamTag() != null && this
						.getParamTag().equals(castOther.getParamTag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNodeId() == null ? 0 : this.getNodeId().hashCode());
		result = 37 * result
				+ (getParamTag() == null ? 0 : this.getParamTag().hashCode());
		return result;
	}

}
