package org.ecnu.oracle.orm;

// Generated 2013-3-7 21:12:37 by Hibernate Tools 3.4.0.CR1

/**
 * ParamVersion generated by hbm2java
 */
public class ParamVersion implements java.io.Serializable {

	private ParamVersionId id;
	private Long lastVersionNo;
	private String lastVerTime;
	private long curVersionNo;
	private String curVerTime;
	private Long nextVersionNo;
	private String nextVerTime;
	private String lastTime;

	public ParamVersion() {
	}

	public ParamVersion(ParamVersionId id, long curVersionNo,
			String curVerTime, String lastTime) {
		this.id = id;
		this.curVersionNo = curVersionNo;
		this.curVerTime = curVerTime;
		this.lastTime = lastTime;
	}

	public ParamVersion(ParamVersionId id, Long lastVersionNo,
			String lastVerTime, long curVersionNo, String curVerTime,
			Long nextVersionNo, String nextVerTime, String lastTime) {
		this.id = id;
		this.lastVersionNo = lastVersionNo;
		this.lastVerTime = lastVerTime;
		this.curVersionNo = curVersionNo;
		this.curVerTime = curVerTime;
		this.nextVersionNo = nextVersionNo;
		this.nextVerTime = nextVerTime;
		this.lastTime = lastTime;
	}

	public ParamVersionId getId() {
		return this.id;
	}

	public void setId(ParamVersionId id) {
		this.id = id;
	}

	public Long getLastVersionNo() {
		return this.lastVersionNo;
	}

	public void setLastVersionNo(Long lastVersionNo) {
		this.lastVersionNo = lastVersionNo;
	}

	public String getLastVerTime() {
		return this.lastVerTime;
	}

	public void setLastVerTime(String lastVerTime) {
		this.lastVerTime = lastVerTime;
	}

	public long getCurVersionNo() {
		return this.curVersionNo;
	}

	public void setCurVersionNo(long curVersionNo) {
		this.curVersionNo = curVersionNo;
	}

	public String getCurVerTime() {
		return this.curVerTime;
	}

	public void setCurVerTime(String curVerTime) {
		this.curVerTime = curVerTime;
	}

	public Long getNextVersionNo() {
		return this.nextVersionNo;
	}

	public void setNextVersionNo(Long nextVersionNo) {
		this.nextVersionNo = nextVersionNo;
	}

	public String getNextVerTime() {
		return this.nextVerTime;
	}

	public void setNextVerTime(String nextVerTime) {
		this.nextVerTime = nextVerTime;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

}
