package org.ecnu.oracle.orm;

// Generated 2013-3-7 21:12:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PGoodsInfo generated by hbm2java
 */
public class PGoodsInfo implements java.io.Serializable {

	private String wareId;
	private String wareName;
	private String wareDesc;
	private Long wholeStorage;
	private String lastTime;
	private Long wareBasePrice;
	private String wareType;
	private Long wareMaxPrice;
	private Long wareMinPrice;
	private String warePyHead;
	private Set<PWareInfo> PWareInfos = new HashSet<PWareInfo>(0);

	public PGoodsInfo() {
	}

	public PGoodsInfo(String wareId, String wareName) {
		this.wareId = wareId;
		this.wareName = wareName;
	}

	public PGoodsInfo(String wareId, String wareName, String wareDesc,
			Long wholeStorage, String lastTime, Long wareBasePrice,
			String wareType, Long wareMaxPrice, Long wareMinPrice,
			String warePyHead, Set<PWareInfo> PWareInfos) {
		this.wareId = wareId;
		this.wareName = wareName;
		this.wareDesc = wareDesc;
		this.wholeStorage = wholeStorage;
		this.lastTime = lastTime;
		this.wareBasePrice = wareBasePrice;
		this.wareType = wareType;
		this.wareMaxPrice = wareMaxPrice;
		this.wareMinPrice = wareMinPrice;
		this.warePyHead = warePyHead;
		this.PWareInfos = PWareInfos;
	}

	public String getWareId() {
		return this.wareId;
	}

	public void setWareId(String wareId) {
		this.wareId = wareId;
	}

	public String getWareName() {
		return this.wareName;
	}

	public void setWareName(String wareName) {
		this.wareName = wareName;
	}

	public String getWareDesc() {
		return this.wareDesc;
	}

	public void setWareDesc(String wareDesc) {
		this.wareDesc = wareDesc;
	}

	public Long getWholeStorage() {
		return this.wholeStorage;
	}

	public void setWholeStorage(Long wholeStorage) {
		this.wholeStorage = wholeStorage;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	public Long getWareBasePrice() {
		return this.wareBasePrice;
	}

	public void setWareBasePrice(Long wareBasePrice) {
		this.wareBasePrice = wareBasePrice;
	}

	public String getWareType() {
		return this.wareType;
	}

	public void setWareType(String wareType) {
		this.wareType = wareType;
	}

	public Long getWareMaxPrice() {
		return this.wareMaxPrice;
	}

	public void setWareMaxPrice(Long wareMaxPrice) {
		this.wareMaxPrice = wareMaxPrice;
	}

	public Long getWareMinPrice() {
		return this.wareMinPrice;
	}

	public void setWareMinPrice(Long wareMinPrice) {
		this.wareMinPrice = wareMinPrice;
	}

	public String getWarePyHead() {
		return this.warePyHead;
	}

	public void setWarePyHead(String warePyHead) {
		this.warePyHead = warePyHead;
	}

	public Set<PWareInfo> getPWareInfos() {
		return this.PWareInfos;
	}

	public void setPWareInfos(Set<PWareInfo> PWareInfos) {
		this.PWareInfos = PWareInfos;
	}

}
