package org.ecnu.oracle.orm;

// Generated 2013-3-7 21:12:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PWareInfoVersion generated by hbm2java
 */
public class PWareInfoVersion implements java.io.Serializable {

	private long versionNo;
	private String name;
	private String des;
	private String username;
	private String lastTime;
	private String equipPassType;
	private String effectTime;
	private String utilityInfo;
	private Set<PWareInfo> PWareInfos = new HashSet<PWareInfo>(0);

	public PWareInfoVersion() {
	}

	public PWareInfoVersion(long versionNo, String name, String effectTime,
			String utilityInfo) {
		this.versionNo = versionNo;
		this.name = name;
		this.effectTime = effectTime;
		this.utilityInfo = utilityInfo;
	}

	public PWareInfoVersion(long versionNo, String name, String des,
			String username, String lastTime, String equipPassType,
			String effectTime, String utilityInfo, Set<PWareInfo> PWareInfos) {
		this.versionNo = versionNo;
		this.name = name;
		this.des = des;
		this.username = username;
		this.lastTime = lastTime;
		this.equipPassType = equipPassType;
		this.effectTime = effectTime;
		this.utilityInfo = utilityInfo;
		this.PWareInfos = PWareInfos;
	}

	public long getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(long versionNo) {
		this.versionNo = versionNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	public String getEquipPassType() {
		return this.equipPassType;
	}

	public void setEquipPassType(String equipPassType) {
		this.equipPassType = equipPassType;
	}

	public String getEffectTime() {
		return this.effectTime;
	}

	public void setEffectTime(String effectTime) {
		this.effectTime = effectTime;
	}

	public String getUtilityInfo() {
		return this.utilityInfo;
	}

	public void setUtilityInfo(String utilityInfo) {
		this.utilityInfo = utilityInfo;
	}

	public Set<PWareInfo> getPWareInfos() {
		return this.PWareInfos;
	}

	public void setPWareInfos(Set<PWareInfo> PWareInfos) {
		this.PWareInfos = PWareInfos;
	}

}
