package org.ecnu.orm;

// Generated 2013-4-19 10:10:02 by Hibernate Tools 3.4.0.CR1

/**
 * Mystock generated by hbm2java
 */
public class MyStock implements java.io.Serializable {

	private Long stockId;
	private String employeeName;
	private String year;
	private String month;
	private String nodeName;
	private String wareName;
	private Integer lastMonthNum;//上月存留数量
	private Integer lastMonthCost;
	private Integer depotWareNum;
	private Integer checkStoreNum;//月末清算时填写的数量
	private Integer checkWareCost;
	private Integer currentWareNum;//销售数据统计的数量
	private Integer depotWareCost;
	private String checkType;//1单台售货机清算；2总清算；3统计
	private String type;//1未清算；2已清算
	private String lastTime;

	public MyStock() {
	}

	public MyStock(String employeeName, String year, String month, Integer lastMonthNum, Integer lastMonthCost,
			String nodeName, String wareName, Integer depotWareNum, Integer checkStoreNum, Integer checkWareCost,
			Integer currentWareNum, Integer depotWareCost, String type,String checkType,
			String lastTime) {
		this.employeeName = employeeName;
		this.year = year;
		this.month = month;
		this.nodeName = nodeName;
		this.wareName = wareName;
		this.lastMonthNum = lastMonthNum;
		this.lastMonthCost = lastMonthCost;
		this.depotWareNum = depotWareNum;
		this.checkStoreNum = checkStoreNum;
		this.checkWareCost = checkWareCost;
		this.currentWareNum = currentWareNum;
		this.depotWareCost = depotWareCost;
		this.checkType = checkType;
		this.type = type;
		this.lastTime = lastTime;
	}

	public Long getStockId() {
		return this.stockId;
	}

	public void setStockId(Long stockId) {
		this.stockId = stockId;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getNodeName() {
		return this.nodeName;
	}

	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

	public String getWareName() {
		return this.wareName;
	}

	public void setWareName(String wareName) {
		this.wareName = wareName;
	}

	public Integer getDepotWareNum() {
		return this.depotWareNum;
	}

	public void setDepotWareNum(Integer depotWareNum) {
		this.depotWareNum = depotWareNum;
	}

	public Integer getCurrentWareNum() {
		return this.currentWareNum;
	}

	public void setCurrentWareNum(Integer currentWareNum) {
		this.currentWareNum = currentWareNum;
	}

	public Integer getDepotWareCost() {
		return this.depotWareCost;
	}

	public void setDepotWareCost(Integer depotWareCost) {
		this.depotWareCost = depotWareCost;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	public Integer getCheckStoreNum() {
		return checkStoreNum;
	}

	public void setCheckStoreNum(Integer checkStoreNum) {
		this.checkStoreNum = checkStoreNum;
	}

	public Integer getCheckWareCost() {
		return checkWareCost;
	}

	public void setCheckWareCost(Integer checkWareCost) {
		this.checkWareCost = checkWareCost;
	}

	public Integer getLastMonthNum() {
		return lastMonthNum;
	}

	public void setLastMonthNum(Integer lastMonthNum) {
		this.lastMonthNum = lastMonthNum;
	}

	public Integer getLastMonthCost() {
		return lastMonthCost;
	}

	public void setLastMonthCost(Integer lastMonthCost) {
		this.lastMonthCost = lastMonthCost;
	}

	public String getCheckType() {
		return checkType;
	}

	public void setCheckType(String checkType) {
		this.checkType = checkType;
	}

}
