package org.ecnu.orm;

// Generated 2013-3-12 14:15:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * NodeGroupInfo generated by hbm2java
 */
public class NodeGroupInfo implements java.io.Serializable {

	private String nodeGroupId;
	private String nodeGroupName;
	private String nodeGroupType;
	private String nodeGroupDesc;
	private String groupParentId;
	private Set<NodeInfo> nodeInfos = new HashSet<NodeInfo>(0);

	public NodeGroupInfo() {
	}

	public NodeGroupInfo(String nodeGroupId) {
		this.nodeGroupId = nodeGroupId;
	}

	public NodeGroupInfo(String nodeGroupId, String nodeGroupName,
			String nodeGroupType, String nodeGroupDesc, String groupParentId,
			Set<NodeInfo> nodeInfos) {
		this.nodeGroupId = nodeGroupId;
		this.nodeGroupName = nodeGroupName;
		this.nodeGroupType = nodeGroupType;
		this.nodeGroupDesc = nodeGroupDesc;
		this.groupParentId = groupParentId;
		this.nodeInfos = nodeInfos;
	}

	public String getNodeGroupId() {
		return this.nodeGroupId;
	}

	public void setNodeGroupId(String nodeGroupId) {
		this.nodeGroupId = nodeGroupId;
	}

	public String getNodeGroupName() {
		return this.nodeGroupName;
	}

	public void setNodeGroupName(String nodeGroupName) {
		this.nodeGroupName = nodeGroupName;
	}

	public String getNodeGroupType() {
		return this.nodeGroupType;
	}

	public void setNodeGroupType(String nodeGroupType) {
		this.nodeGroupType = nodeGroupType;
	}

	public String getNodeGroupDesc() {
		return this.nodeGroupDesc;
	}

	public void setNodeGroupDesc(String nodeGroupDesc) {
		this.nodeGroupDesc = nodeGroupDesc;
	}

	public String getGroupParentId() {
		return this.groupParentId;
	}

	public void setGroupParentId(String groupParentId) {
		this.groupParentId = groupParentId;
	}

	public Set<NodeInfo> getNodeInfos() {
		return this.nodeInfos;
	}

	public void setNodeInfos(Set<NodeInfo> nodeInfos) {
		this.nodeInfos = nodeInfos;
	}

}
