package org.ecnu.orm;

// Generated 2013-5-12 21:32:06 by Hibernate Tools 3.4.0.CR1

/**
 * Sale generated by hbm2java
 */
public class Sale implements java.io.Serializable {

	private Long saleId;
	private String year;
	private String month;
	private String day;
	private String employeeName;
	private String nodeId;
	private String nodeName;
	private String channelId;
	private String wareName;
	private Integer saleNum;
	private Integer salePrice;
	private Integer thoeryPrice;
	private String type;
	private String lastTime;

	public Sale() {
	}

	public Sale(String employeeName) {
		this.employeeName = employeeName;
	}

	public Sale(String year, String month, String day, String employeeName,
			String nodeId, String nodeName, String channelId, String wareName,
			Integer saleNum, Integer salePrice, Integer thoeryPrice, String type,
			String lastTime) {
		this.year = year;
		this.month = month;
		this.day = day;
		this.employeeName = employeeName;
		this.nodeId = nodeId;
		this.nodeName = nodeName;
		this.channelId = channelId;
		this.wareName = wareName;
		this.saleNum = saleNum;
		this.salePrice = salePrice;
		this.thoeryPrice = thoeryPrice;
		this.type = type;
		this.lastTime = lastTime;
	}

	public Long getSaleId() {
		return this.saleId;
	}

	public void setSaleId(Long saleId) {
		this.saleId = saleId;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(String nodeId) {
		this.nodeId = nodeId;
	}

	public String getNodeName() {
		return this.nodeName;
	}

	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

	public String getChannelId() {
		return this.channelId;
	}

	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

	public String getWareName() {
		return this.wareName;
	}

	public void setWareName(String wareName) {
		this.wareName = wareName;
	}

	public Integer getSaleNum() {
		return this.saleNum;
	}

	public void setSaleNum(Integer saleNum) {
		this.saleNum = saleNum;
	}

	public Integer getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(Integer salePrice) {
		this.salePrice = salePrice;
	}

	public Integer getThoeryPrice() {
		return this.thoeryPrice;
	}

	public void setThoeryPrice(Integer thoeryPrice) {
		this.thoeryPrice = thoeryPrice;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
