package org.ecnu.orm;

// Generated 2013-4-27 15:05:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Shipping generated by hbm2java
 */
public class Shipping implements java.io.Serializable {

	private Long id;
	private String shippingId;
	private String employeeName;
	private String depotDay;
	private Integer moneyThis;
	private Integer moneyAll;
	private String humanName;
	private String wareHouse;
	private String driverName;
	private String operator;
	private String tableor;
	private String remark;
	private String lastTime;
	private Set<Depot> depots = new HashSet<Depot>(0);

	public Shipping() {
	}

	public Shipping(String shippingId, String employeeName) {
		this.shippingId = shippingId;
		this.employeeName = employeeName;
	}

	public Shipping(String shippingId, String employeeName, Integer moneyThis, String depotDay,
			Integer moneyAll, String humanName, String wareHouse,
			String driverName, String operator, String tableor, String remark,
			String lastTime, Set<Depot> depots) {
		this.shippingId = shippingId;
		this.employeeName = employeeName;
		this.moneyThis = moneyThis;
		this.moneyAll = moneyAll;
		this.humanName = humanName;
		this.wareHouse = wareHouse;
		this.driverName = driverName;
		this.operator = operator;
		this.tableor = tableor;
		this.remark = remark;
		this.lastTime = lastTime;
		this.depotDay = depotDay;
		this.depots = depots;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getShippingId() {
		return this.shippingId;
	}

	public void setShippingId(String shippingId) {
		this.shippingId = shippingId;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public Integer getMoneyThis() {
		return this.moneyThis;
	}

	public void setMoneyThis(Integer moneyThis) {
		this.moneyThis = moneyThis;
	}

	public Integer getMoneyAll() {
		return this.moneyAll;
	}

	public void setMoneyAll(Integer moneyAll) {
		this.moneyAll = moneyAll;
	}

	public String getHumanName() {
		return this.humanName;
	}

	public void setHumanName(String humanName) {
		this.humanName = humanName;
	}

	public String getWareHouse() {
		return this.wareHouse;
	}

	public void setWareHouse(String wareHouse) {
		this.wareHouse = wareHouse;
	}

	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getTableor() {
		return this.tableor;
	}

	public void setTableor(String tableor) {
		this.tableor = tableor;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	public Set<Depot> getDepots() {
		return this.depots;
	}

	public void setDepots(Set<Depot> depots) {
		this.depots = depots;
	}

	public String getDepotDay() {
		return depotDay;
	}

	public void setDepotDay(String depotDay) {
		this.depotDay = depotDay;
	}

}
