package org.ecnu.orm;

// Generated 2013-4-13 12:14:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UserGroup generated by hbm2java
 */
public class UserGroup implements java.io.Serializable {

	private Long groupId;
	private String groupType;
	private String groupName;
	private String groupLeader;
	private String groupDesc;
	private Long parentId;
	private Integer groupNumber;
	private Set<Users> userses = new HashSet<Users>(0);

	public UserGroup() {
	}

	public UserGroup(String groupType, String groupName, String groupLeader,
			String groupDesc, Long parentId, Integer groupNumber,
			Set<Users> userses) {
		this.groupType = groupType;
		this.groupName = groupName;
		this.groupLeader = groupLeader;
		this.groupDesc = groupDesc;
		this.parentId = parentId;
		this.groupNumber = groupNumber;
		this.userses = userses;
	}

	public Long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	public String getGroupType() {
		return this.groupType;
	}

	public void setGroupType(String groupType) {
		this.groupType = groupType;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getGroupLeader() {
		return this.groupLeader;
	}

	public void setGroupLeader(String groupLeader) {
		this.groupLeader = groupLeader;
	}

	public String getGroupDesc() {
		return this.groupDesc;
	}

	public void setGroupDesc(String groupDesc) {
		this.groupDesc = groupDesc;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public Integer getGroupNumber() {
		return this.groupNumber;
	}

	public void setGroupNumber(Integer groupNumber) {
		this.groupNumber = groupNumber;
	}

	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
