package org.ecnu.orm;

// Generated 2013-3-12 14:15:56 by Hibernate Tools 3.4.0.CR1

/**
 * WareInfo generated by hbm2java
 */
public class WareInfo implements java.io.Serializable {

	private String wareId;
	private String wareName;
	private String wareSimpleCode;
	private String wareDesc;

	public WareInfo() {
	}

	public WareInfo(String wareId) {
		this.wareId = wareId;
	}

	public WareInfo(String wareId, String wareName, String wareSimpleCode,
			String wareDesc) {
		this.wareId = wareId;
		this.wareName = wareName;
		this.wareSimpleCode = wareSimpleCode;
		this.wareDesc = wareDesc;
	}

	public String getWareId() {
		return this.wareId;
	}

	public void setWareId(String wareId) {
		this.wareId = wareId;
	}

	public String getWareName() {
		return this.wareName;
	}

	public void setWareName(String wareName) {
		this.wareName = wareName;
	}

	public String getWareSimpleCode() {
		return this.wareSimpleCode;
	}

	public void setWareSimpleCode(String wareSimpleCode) {
		this.wareSimpleCode = wareSimpleCode;
	}

	public String getWareDesc() {
		return this.wareDesc;
	}

	public void setWareDesc(String wareDesc) {
		this.wareDesc = wareDesc;
	}

}
