package org.ecnu.oracle.orm;

// Generated 2013-3-7 21:12:37 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * OpTemp generated by hbm2java
 */
public class OpTemp implements java.io.Serializable {

	private BigDecimal id;
	private String tableName;
	private String recordId;
	private Character op;
	private String lastTime;

	public OpTemp() {
	}

	public OpTemp(BigDecimal id, String tableName, String recordId,
			String lastTime) {
		this.id = id;
		this.tableName = tableName;
		this.recordId = recordId;
		this.lastTime = lastTime;
	}

	public OpTemp(BigDecimal id, String tableName, String recordId,
			Character op, String lastTime) {
		this.id = id;
		this.tableName = tableName;
		this.recordId = recordId;
		this.op = op;
		this.lastTime = lastTime;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getRecordId() {
		return this.recordId;
	}

	public void setRecordId(String recordId) {
		this.recordId = recordId;
	}

	public Character getOp() {
		return this.op;
	}

	public void setOp(Character op) {
		this.op = op;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

}
