package org.ecnu.oracle.orm;

// Generated 2013-3-7 21:12:37 by Hibernate Tools 3.4.0.CR1

/**
 * RptTxnDtlId generated by hbm2java
 */
public class RptTxnDtlId implements java.io.Serializable {

	private String workDate;
	private int batchNo;
	private String posId;
	private String txnEventCode;
	private String passNo;
	private String salesId;

	public RptTxnDtlId() {
	}

	public RptTxnDtlId(String workDate, int batchNo, String posId,
			String txnEventCode, String passNo, String salesId) {
		this.workDate = workDate;
		this.batchNo = batchNo;
		this.posId = posId;
		this.txnEventCode = txnEventCode;
		this.passNo = passNo;
		this.salesId = salesId;
	}

	public String getWorkDate() {
		return this.workDate;
	}

	public void setWorkDate(String workDate) {
		this.workDate = workDate;
	}

	public int getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(int batchNo) {
		this.batchNo = batchNo;
	}

	public String getPosId() {
		return this.posId;
	}

	public void setPosId(String posId) {
		this.posId = posId;
	}

	public String getTxnEventCode() {
		return this.txnEventCode;
	}

	public void setTxnEventCode(String txnEventCode) {
		this.txnEventCode = txnEventCode;
	}

	public String getPassNo() {
		return this.passNo;
	}

	public void setPassNo(String passNo) {
		this.passNo = passNo;
	}

	public String getSalesId() {
		return this.salesId;
	}

	public void setSalesId(String salesId) {
		this.salesId = salesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RptTxnDtlId))
			return false;
		RptTxnDtlId castOther = (RptTxnDtlId) other;

		return ((this.getWorkDate() == castOther.getWorkDate()) || (this
				.getWorkDate() != null && castOther.getWorkDate() != null && this
				.getWorkDate().equals(castOther.getWorkDate())))
				&& (this.getBatchNo() == castOther.getBatchNo())
				&& ((this.getPosId() == castOther.getPosId()) || (this
						.getPosId() != null && castOther.getPosId() != null && this
						.getPosId().equals(castOther.getPosId())))
				&& ((this.getTxnEventCode() == castOther.getTxnEventCode()) || (this
						.getTxnEventCode() != null
						&& castOther.getTxnEventCode() != null && this
						.getTxnEventCode().equals(castOther.getTxnEventCode())))
				&& ((this.getPassNo() == castOther.getPassNo()) || (this
						.getPassNo() != null && castOther.getPassNo() != null && this
						.getPassNo().equals(castOther.getPassNo())))
				&& ((this.getSalesId() == castOther.getSalesId()) || (this
						.getSalesId() != null && castOther.getSalesId() != null && this
						.getSalesId().equals(castOther.getSalesId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getWorkDate() == null ? 0 : this.getWorkDate().hashCode());
		result = 37 * result + this.getBatchNo();
		result = 37 * result
				+ (getPosId() == null ? 0 : this.getPosId().hashCode());
		result = 37
				* result
				+ (getTxnEventCode() == null ? 0 : this.getTxnEventCode()
						.hashCode());
		result = 37 * result
				+ (getPassNo() == null ? 0 : this.getPassNo().hashCode());
		result = 37 * result
				+ (getSalesId() == null ? 0 : this.getSalesId().hashCode());
		return result;
	}

}
