package org.ecnu.oracle.orm;

// Generated 2013-3-7 21:12:37 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * RptTxnDtl generated by hbm2java
 */
public class RptTxnDtl implements java.io.Serializable {

	private RptTxnDtlId id;
	private BigDecimal outNum;
	private BigDecimal adverClick;
	private BigDecimal amout;
	private String reserved1;
	private String lastTime;
	private BigDecimal insertAmount;
	private BigDecimal changeAmount;
	private String belongTo;

	public RptTxnDtl() {
	}

	public RptTxnDtl(RptTxnDtlId id) {
		this.id = id;
	}

	public RptTxnDtl(RptTxnDtlId id, BigDecimal outNum, BigDecimal adverClick,
			BigDecimal amout, String reserved1, String lastTime,
			BigDecimal insertAmount, BigDecimal changeAmount, String belongTo) {
		this.id = id;
		this.outNum = outNum;
		this.adverClick = adverClick;
		this.amout = amout;
		this.reserved1 = reserved1;
		this.lastTime = lastTime;
		this.insertAmount = insertAmount;
		this.changeAmount = changeAmount;
		this.belongTo = belongTo;
	}

	public RptTxnDtlId getId() {
		return this.id;
	}

	public void setId(RptTxnDtlId id) {
		this.id = id;
	}

	public BigDecimal getOutNum() {
		return this.outNum;
	}

	public void setOutNum(BigDecimal outNum) {
		this.outNum = outNum;
	}

	public BigDecimal getAdverClick() {
		return this.adverClick;
	}

	public void setAdverClick(BigDecimal adverClick) {
		this.adverClick = adverClick;
	}

	public BigDecimal getAmout() {
		return this.amout;
	}

	public void setAmout(BigDecimal amout) {
		this.amout = amout;
	}

	public String getReserved1() {
		return this.reserved1;
	}

	public void setReserved1(String reserved1) {
		this.reserved1 = reserved1;
	}

	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	public BigDecimal getInsertAmount() {
		return this.insertAmount;
	}

	public void setInsertAmount(BigDecimal insertAmount) {
		this.insertAmount = insertAmount;
	}

	public BigDecimal getChangeAmount() {
		return this.changeAmount;
	}

	public void setChangeAmount(BigDecimal changeAmount) {
		this.changeAmount = changeAmount;
	}

	public String getBelongTo() {
		return this.belongTo;
	}

	public void setBelongTo(String belongTo) {
		this.belongTo = belongTo;
	}

}
